"""
Scan models — WebSocket message schemas for the live-scan pipeline.

All models are Pydantic v2 BaseModels used to validate the JSON
messages flowing between the frontend and the ``WS /ws/scan`` endpoint.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class BoundingBox(BaseModel):
    """Normalised bounding-box coordinates (values in [0, 1])."""

    x: float = Field(..., ge=0.0, le=1.0)
    y: float = Field(..., ge=0.0, le=1.0)
    width: float = Field(..., gt=0.0, le=1.0)
    height: float = Field(..., gt=0.0, le=1.0)
    mediapipe_label: str = Field(default="object")
    detection_score: float = Field(default=0.0, ge=0.0, le=1.0)


class ScanRegion(BaseModel):
    """One cropped region from a single bounding box."""

    cropped_image_b64: str = Field(..., description="Base64-encoded cropped image")
    bbox: BoundingBox


class ScanFrame(BaseModel):
    """Inbound WebSocket message — one key-frame with all detected regions."""

    grid_id: str | None = None
    frame_number: int = Field(default=0, ge=0)
    base64_image: str | None = Field(
        default=None,
        description="Optional full-frame image (raw base64 or data URL) for server-side region detection",
    )
    regions: list[ScanRegion] = Field(
        default_factory=list,
        description="Optional pre-cropped regions. If empty, server can auto-detect from base64_image.",
    )


class ScanResult(BaseModel):
    """Diagnosis output for one cropped region."""

    cropType: str = Field(default="Unknown", description="Type of plant or 'Pest'")
    disease: str = Field(default="Healthy", description="Disease or pest name")
    severity: str = Field(default="Low", description="High, Moderate, or Low")
    severityScore: float = Field(default=0.0, ge=0.0, le=1.0)
    treatmentPlan: str = Field(default="None")
    survivalProb: float = Field(default=1.0, ge=0.0, le=1.0)
    is_abnormal: bool = Field(default=False)
    bbox: BoundingBox


class ScanResponse(BaseModel):
    """Outbound WebSocket message — results for every region in the frame."""

    frame_number: int
    results: list[ScanResult]


class HttpScanRequest(BaseModel):
    """Inbound REST request for one capture frame from the frontend."""

    source: str = Field(default="camera")
    grid_id: str | None = None
    base64_image: str = Field(..., min_length=16, description="Raw base64 or data URL image")


class HttpScanResponse(BaseModel):
    """Frontend-facing response contract for single-frame diagnosis."""

    disease: str
    severity: int = Field(..., ge=0, le=100)
    confidence: int = Field(..., ge=0, le=100)
    spread_risk: str
    zone: str | None = None
    crop_type: str = Field(default="Unknown")
    treatment_plan: str = Field(default="Consult Agrologist")


class HttpScanAssistantRequest(HttpScanRequest):
    """Scan request that also asks assistant to generate a dialogue reply."""

    user_prompt: str = Field(
        default="I just took this photo. Please explain the diagnosis and what to do next.",
    )


class HttpScanAssistantResponse(HttpScanResponse):
    """Scan response enriched with assistant dialogue generated by Gemini."""

    assistant_reply: str


class HttpScanRegion(BaseModel):
    """One cropped region for multi-region assistant scanning."""

    cropped_image_b64: str = Field(..., description="Base64-encoded cropped image")
    bbox: BoundingBox = Field(default_factory=lambda: BoundingBox(x=0, y=0, width=1, height=1))


class HttpScanAssistantMultiRequest(BaseModel):
    """Multi-region scan request for chatbot to handle multiple crops/plants in one photo."""

    source: str = Field(default="camera")
    grid_id: str | None = None
    regions: list[HttpScanRegion] = Field(..., min_length=1, description="Cropped regions to diagnose")
    user_prompt: str = Field(
        default="I just took this photo. Please analyze all detected crops and tell me what to do.",
    )


class HttpScanAssistantMultiResponse(BaseModel):
    """Multi-region scan response with consolidated assistant dialogue."""

    frame_number: int = Field(default=0)
    regions_results: list[HttpScanResponse] = Field(description="Diagnosis for each region")
    consolidated_assistant_reply: str = Field(description="Assistant dialogue addressing all regions")
