"""
Scan models — WebSocket message schemas for the live-scan pipeline.

All models are Pydantic v2 BaseModels used to validate the JSON
messages flowing between the frontend and the ``WS /ws/scan`` endpoint.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class BoundingBox(BaseModel):
    """Normalised bounding-box coordinates (values in [0, 1])."""

    x: float = Field(..., ge=0.0, le=1.0)
    y: float = Field(..., ge=0.0, le=1.0)
    width: float = Field(..., gt=0.0, le=1.0)
    height: float = Field(..., gt=0.0, le=1.0)
    mediapipe_label: str = Field(default="object")
    detection_score: float = Field(default=0.0, ge=0.0, le=1.0)


class ScanRegion(BaseModel):
    """One cropped region from a single bounding box."""

    cropped_image_b64: str = Field(..., description="Base64-encoded cropped image")
    bbox: BoundingBox


class ScanFrame(BaseModel):
    """Inbound WebSocket message — one key-frame with all detected regions."""

    grid_id: str | None = None
    frame_number: int = Field(default=0, ge=0)
    base64_image: str | None = Field(
        default=None,
        description="Optional full-frame image (raw base64 or data URL) for server-side region detection",
    )
    regions: list[ScanRegion] = Field(
        default_factory=list,
        description="Optional pre-cropped regions. If empty, server can auto-detect from base64_image.",
    )


class ScanResult(BaseModel):
    """Diagnosis output for one cropped region."""

    cropType: str = Field(default="Unknown", description="Type of plant or 'Pest'")
    disease: str = Field(default="Healthy", description="Disease or pest name")
    severity: str = Field(default="Low", description="High, Moderate, or Low")
    severityScore: float = Field(default=0.0, ge=0.0, le=1.0)
    treatmentPlan: str = Field(default="None")
    survivalProb: float = Field(default=1.0, ge=0.0, le=1.0)
    is_abnormal: bool = Field(default=False)
    recommendedPesticides: list[str] = Field(default_factory=list)
    recommendationSource: str | None = None
    matchedPestName: str | None = None
    bbox: BoundingBox


class ScanResponse(BaseModel):
    """Outbound WebSocket message — results for every region in the frame."""

    frame_number: int
    results: list[ScanResult]


class HttpScanRequest(BaseModel):
    """Inbound REST request for one capture frame from the frontend."""

    source: str = Field(default="camera")
    grid_id: str | None = None
    user_id: str | None = None
    base64_image: str = Field(..., min_length=16, description="Raw base64 or data URL image")


class HttpScanResponse(BaseModel):
    """Frontend-facing response contract for single-frame diagnosis."""

    disease: str
    severity: int = Field(..., ge=0, le=100)
    confidence: int = Field(..., ge=0, le=100)
    spread_risk: str
    zone: str | None = None
    crop_type: str = Field(default="Unknown")
    treatment_plan: str = Field(default="Consult Agrologist")
    recommended_pesticides: list[str] = Field(default_factory=list)
    recommendation_source: str | None = None
    matched_pest_name: str | None = None


class HttpScanAssistantRequest(HttpScanRequest):
    """Scan request that also asks assistant to generate a dialogue reply."""

    user_prompt: str = Field(
        default="I just took this photo. Please explain the diagnosis and what to do next.",
    )


class HttpScanAssistantResponse(HttpScanResponse):
    """Scan response enriched with assistant dialogue generated by Gemini."""

    assistant_reply: str


class HttpScanRegion(BaseModel):
    """One cropped region for multi-region assistant scanning."""

    cropped_image_b64: str = Field(..., description="Base64-encoded cropped image")
    bbox: BoundingBox = Field(default_factory=lambda: BoundingBox(x=0, y=0, width=1, height=1))


class HttpScanAssistantMultiRequest(BaseModel):
    """Multi-region scan request for chatbot to handle multiple crops/plants in one photo."""

    source: str = Field(default="camera")
    grid_id: str | None = None
    user_id: str | None = None
    regions: list[HttpScanRegion] = Field(..., min_length=1, description="Cropped regions to diagnose")
    user_prompt: str = Field(
        default="I just took this photo. Please analyze all detected crops and tell me what to do.",
    )


class HttpScanAssistantMultiResponse(BaseModel):
    """Multi-region scan response with consolidated assistant dialogue."""

    frame_number: int = Field(default=0)
    regions_results: list[HttpScanResponse] = Field(description="Diagnosis for each region")
    consolidated_assistant_reply: str = Field(description="Assistant dialogue addressing all regions")


class HourlyEntry(BaseModel):
    """One hour slot within a forecast day."""

    time: str
    temperature_c: int
    rain_chance: int = Field(..., ge=0, le=100)
    wind_kmh: int
    condition: str
    safe_to_spray: bool


class WeatherForecastEntry(BaseModel):
    """One day forecast entry for weather page rendering."""

    date: str | None = None
    day: str
    condition: str
    rainChance: int = Field(..., ge=0, le=100)
    wind: str
    sprayWindow: str
    safe: bool
    temperature_high: int | None = None
    temperature_low: int | None = None
    hourly: list[HourlyEntry] = Field(default_factory=list)


class WeatherOutlookResponse(BaseModel):
    """Weather response used by dashboard and weather pages."""

    rain_probability: int = Field(..., ge=0, le=100)
    best_spray_window: str
    advisory: str
    condition: str
    temperatureC: int
    windKmh: int
    windDirection: str
    rainInHours: float | None = None
    safeToSpray: bool
    forecast: list[WeatherForecastEntry] = Field(default_factory=list)
    serviceWarning: str | None = None


class WeatherV1Response(BaseModel):
    """Simplified weather payload for v1 dashboard widget contract."""

    temperature: float
    humidity: int = Field(..., ge=0, le=100)
    wind_speed: float = Field(..., ge=0.0)
    rain_probability: int = Field(..., ge=0, le=100)
    safe_to_spray: bool
    recommendation: str
    serviceWarning: str | None = None


class TreatmentPlanRequest(BaseModel):
    """Input contract for treatment and ROI analysis."""

    user_id: str = Field(..., min_length=1)
    crop_id: str | None = None
    disease: str = Field(default="Crop disease risk", min_length=1)
    zone: str | None = None
    crop_type: str | None = None
    treatment_plan: str | None = None
    farm_size_hectares: float | None = Field(default=None, gt=0)
    survival_prob: float = Field(default=1.0, ge=0.0, le=1.0)
    lat: float | None = None
    lng: float | None = None
    weatherContext: str | None = None
    treatment_cost_rm: float | None = Field(default=None, ge=0.0)
    selling_channel: str = Field(default="middleman", min_length=1)
    market_condition: str = Field(default="normal", min_length=1)
    manual_price_override: float | None = Field(default=None, ge=0.0)
    yield_kg: float | None = Field(default=None, ge=0.0)
    actual_sold_kg: float | None = Field(default=None, ge=0.0)
    labor_cost_rm: float | None = Field(default=None, ge=0.0)
    other_costs_rm: float | None = Field(default=None, ge=0.0)


class TreatmentPlanResponse(BaseModel):
    """Output contract for treatment recommendation and ROI."""

    recommendation: str
    estimated_cost_rm: float = Field(..., ge=0.0)
    expected_gain_rm: float = Field(..., ge=0.0)
    roi_x: float | None = Field(default=None, ge=0.0)
    organic_alternative: str
    retail_price_rm_per_kg: float | None = Field(default=None, ge=0.0)
    farm_price_rm_per_kg: float | None = Field(default=None, ge=0.0)
    price_date: str | None = None
    yield_kg: float | None = Field(default=None, ge=0.0)
    actual_sold_kg: float | None = Field(default=None, ge=0.0)
    inventory_cost_rm: float | None = Field(default=None, ge=0.0)
    inventory_breakdown: list[dict] = Field(default_factory=list)
    labor_cost_rm: float | None = Field(default=None, ge=0.0)
    other_costs_rm: float | None = Field(default=None, ge=0.0)
    profit_rm: float | None = None
    roi_percent: float | None = None
    roi_note: str | None = None
    selling_channel: str | None = None
    market_condition: str | None = None
    used_manual_price_override: bool = False


class InventoryItemResponse(BaseModel):
    """Inventory item exposed to frontend inventory page."""

    id: str
    name: str
    description: str | None = None
    category: str
    liters: float = Field(..., ge=0.0)
    unit_cost_rm: float = Field(default=0.0, ge=0.0)
    last_updated_iso: str | None = None


class InventoryListResponse(BaseModel):
    """List payload for inventory page."""

    items: list[InventoryItemResponse] = Field(default_factory=list)
    total_items: int = Field(..., ge=0)
    low_stock_count: int = Field(..., ge=0)
    last_updated_iso: str | None = None


class InventoryUpdateRequest(BaseModel):
    """Patch payload for inventory quantity updates."""

    user_id: str = Field(..., min_length=1)
    liters: float = Field(..., ge=0.0)
    description: str | None = None
    unit_cost_rm: float | None = Field(default=None, ge=0.0)
    name: str | None = None
    category: str | None = None


class InventoryUpdateResponse(BaseModel):
    """Result of inventory update operation."""

    id: str
    liters: float = Field(..., ge=0.0)
    description: str | None = None
    unit_cost_rm: float = Field(default=0.0, ge=0.0)
    updated: bool


class InventoryCreateRequest(BaseModel):
    """Payload for creating an inventory item in v1 endpoints."""

    user_id: str = Field(..., min_length=1)
    name: str = Field(..., min_length=1)
    quantity: float = Field(..., ge=0.0)
    usage: str = Field(..., min_length=1)
    unit: str = Field(..., min_length=1)
    cost_per_unit_rm: float = Field(default=0.0, ge=0.0)


class InventoryCreateResponse(BaseModel):
    """Response returned after creating an inventory item."""

    success: bool = True
    item: "InventoryV1ItemResponse"


class InventoryStockUpdateRequest(BaseModel):
    """Delta-based stock patch payload for v1 endpoints."""

    user_id: str = Field(..., min_length=1)
    quantity_change: float


class InventoryV1ItemResponse(BaseModel):
    """Canonical v1 inventory item shape."""

    id: str
    name: str
    description: str | None = None
    quantity: float = Field(..., ge=0.0)
    usage: str
    unit: str
    cost_per_unit_rm: float = Field(default=0.0, ge=0.0)
    created_at: str | None = None
    updated_at: str | None = None


class InventoryV1ListResponse(BaseModel):
    """Canonical v1 list payload sorted by updated_at descending."""

    items: list[InventoryV1ItemResponse] = Field(default_factory=list)


class InventoryStockUpdateResponse(BaseModel):
    """Result of a delta stock update operation in v1."""

    success: bool = True
    item: InventoryV1ItemResponse


class InventoryDeleteResponse(BaseModel):
    """Result of deleting an inventory item."""

    success: bool = True
    id: str
    deleted: bool


class CropInventoryUsageItem(BaseModel):
    """One inventory line-item used by a specific crop cycle."""

    inventory_id: str = Field(..., min_length=1)
    quantity_used: float = Field(..., ge=0.0)


class CropItemResponse(BaseModel):
    """Crop profile used for ROI and farm planning."""

    id: str
    name: str
    expected_yield_kg: float = Field(..., ge=0.0)
    area_hectares: float = Field(default=0.0, ge=0.0)
    planting_date: str | None = None
    status: str = Field(default="growing")
    crop_inventory_usage: list[CropInventoryUsageItem] = Field(default_factory=list)
    labor_cost_rm: float = Field(default=0.0, ge=0.0)
    other_costs_rm: float = Field(default=0.0, ge=0.0)
    last_price_rm_per_kg: float | None = Field(default=None, ge=0.0)
    price_date: str | None = None
    created_at: str | None = None
    updated_at: str | None = None


class CropListResponse(BaseModel):
    """List payload for crop management UI."""

    items: list[CropItemResponse] = Field(default_factory=list)


class CropCreateRequest(BaseModel):
    """Payload for creating a user crop."""

    user_id: str = Field(..., min_length=1)
    name: str = Field(..., min_length=1)
    expected_yield_kg: float = Field(..., ge=0.0)
    area_hectares: float = Field(default=0.0, ge=0.0)
    planting_date: str | None = None
    status: str = Field(default="growing")
    crop_inventory_usage: list[CropInventoryUsageItem] = Field(default_factory=list)
    labor_cost_rm: float = Field(default=0.0, ge=0.0)
    other_costs_rm: float = Field(default=0.0, ge=0.0)


class CropCreateResponse(BaseModel):
    """Result of creating a crop."""

    success: bool = True
    item: CropItemResponse


class CropUpdateRequest(BaseModel):
    """Patch payload for crop updates."""

    user_id: str = Field(..., min_length=1)
    name: str | None = None
    expected_yield_kg: float | None = Field(default=None, ge=0.0)
    area_hectares: float | None = Field(default=None, ge=0.0)
    planting_date: str | None = None
    status: str | None = None
    crop_inventory_usage: list[CropInventoryUsageItem] | None = None
    labor_cost_rm: float | None = Field(default=None, ge=0.0)
    other_costs_rm: float | None = Field(default=None, ge=0.0)


class CropUpdateResponse(BaseModel):
    """Result of updating a crop."""

    success: bool = True
    item: CropItemResponse


class CropDeleteResponse(BaseModel):
    """Result of deleting a crop."""

    success: bool = True
    id: str
    deleted: bool


class DashboardSummaryRequest(BaseModel):
    """Input contract for dashboard aggregate endpoint."""

    user_id: str = Field(..., min_length=1)
    crop_type: str = Field(..., min_length=1)
    treatment_plan: str = Field(..., min_length=1)
    farm_size_hectares: float = Field(..., gt=0)
    survival_prob: float = Field(..., ge=0.0, le=1.0)
    lat: float | None = None
    lng: float | None = None


class DashboardWeatherSnapshot(BaseModel):
    """Dashboard weather snapshot block."""

    condition: str
    temperatureC: int
    windKmh: int
    windDirection: str
    rainInHours: float | None = None
    serviceWarning: str | None = None


class DashboardZoneHealthSummary(BaseModel):
    """Dashboard zone health block."""

    totalAreaHectares: float = Field(..., ge=0.0)
    healthy: int = Field(..., ge=0, le=100)
    atRisk: int = Field(..., ge=0, le=100)
    infected: int = Field(..., ge=0, le=100)
    zonesNeedingAttention: int = Field(..., ge=0)


class DashboardFinancialSummary(BaseModel):
    """Dashboard financial block."""

    roiPercent: float
    projectedRoiValueRm: float
    projectedYieldGainRm: float
    treatmentCostRm: float
    lowStockItem: str | None = None
    lowStockLiters: float | None = None


class DashboardSummaryResponse(BaseModel):
    """Dashboard aggregate response payload."""

    weatherSnapshot: DashboardWeatherSnapshot
    zoneHealthSummary: DashboardZoneHealthSummary
    financialSummary: DashboardFinancialSummary


class ZoneHealthSummaryResponse(BaseModel):
    """Zone health counters for dashboard summary cards."""

    total_zones: int = Field(..., ge=0)
    healthy: int = Field(..., ge=0)
    warning: int = Field(..., ge=0)
    unhealthy: int = Field(..., ge=0)


class StandardErrorResponse(BaseModel):
    """Structured API error payload."""

    success: bool = False
    error: str


class AssistantConversationMessage(BaseModel):
    """Lightweight chat message context for multi-turn assistant replies."""

    role: Literal["user", "ai"]
    text: str = Field(..., min_length=1, max_length=1200)


class AssistantMessageRequest(BaseModel):
    """Input contract for text-only assistant interaction."""

    user_prompt: str = Field(..., min_length=1)
    user_id: str = Field(..., min_length=1)
    zone: str | None = None
    location: str | None = None
    lat: float | None = None
    lng: float | None = None
    conversation_id: str | None = None
    recent_messages: list[AssistantConversationMessage] = Field(default_factory=list, max_length=20)


class AssistantMessageResponse(BaseModel):
    """Output contract for text-only assistant interaction."""

    assistant_reply: str
